feat: only use sudo if necessary
Signed-off-by: Paul Schroeder <milkpirate@users.noreply.github.com>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -48,7 +48,10 @@ inputs:
     description: |
       Applies removal relative to the given directory (helpful for freeing up from within a custom image).
       
-      large-packages, docker-images, tool-cache and swap-storage will still apply to the root within the custom image.
+      If one mounts the docker socket to the guest and if the docker CLI is also installed, docker-images will work
+      as well.
+      
+      large-packages, tool-cache and swap-storage will still apply to the root within the custom image.
     required: false
     default: ""
 
@@ -57,7 +60,6 @@ runs:
   steps:
     - shell: bash
       run: |
-
         # ======
         # MACROS
         # ======
@@ -121,7 +123,18 @@ runs:
           printSeparationLine '=' 80
         }
 
-
+        # to run depending on already being root/sudo is available 
+        run() {
+          # sudo necessary?
+          if [[ $EUID -eq 0 ]]; then
+            "$@"
+          elif command -v sudo >/dev/null 2>&1 && sudo -n true 2>/dev/null; then
+            sudo "$@"
+          else
+            echo "Warning: sudo unavailable, running without: $@"
+            "$@"
+          fi
+        }
 
         # ======
         # SCRIPT
@@ -135,13 +148,12 @@ runs:
         printDH "BEFORE CLEAN-UP:"
         echo ""
 
-
         # Option: Remove Android library
 
         if [[ ${{ inputs.android }} == 'true' ]]; then
           BEFORE=$(getAvailableSpace '${{ inputs.chroot }}')
           
-          sudo rm -rf '${{ inputs.chroot }}/usr/local/lib/android' || true
+          run rm -rf '${{ inputs.chroot }}/usr/local/lib/android' || true
 
           AFTER=$(getAvailableSpace '${{ inputs.chroot }}')
           SAVED=$((AFTER-BEFORE))
@@ -154,7 +166,7 @@ runs:
           BEFORE=$(getAvailableSpace '${{ inputs.chroot }}')
 
           # https://github.community/t/bigger-github-hosted-runners-disk-space/17267/11
-          sudo rm -rf '${{ inputs.chroot }}/usr/share/dotnet' || true
+          run rm -rf '${{ inputs.chroot }}/usr/share/dotnet' || true
           
           AFTER=$(getAvailableSpace '${{ inputs.chroot }}')
           SAVED=$((AFTER-BEFORE))
@@ -166,8 +178,8 @@ runs:
         if [[ ${{ inputs.haskell }} == 'true' ]]; then
           BEFORE=$(getAvailableSpace '${{ inputs.chroot }}')
 
-          sudo rm -rf '${{ inputs.chroot }}/opt/ghc' || true
-          sudo rm -rf '${{ inputs.chroot }}/usr/local/.ghcup' || true
+          run rm -rf '${{ inputs.chroot }}/opt/ghc' || true
+          run rm -rf '${{ inputs.chroot }}/usr/local/.ghcup' || true
           
           AFTER=$(getAvailableSpace '${{ inputs.chroot }}')
           SAVED=$((AFTER-BEFORE))
@@ -180,17 +192,17 @@ runs:
         if [[ ${{ inputs.large-packages }} == 'true' ]]; then
           BEFORE=$(getAvailableSpace)
           
-          sudo apt-get remove -y '^aspnetcore-.*' || echo "::warning::The command [sudo apt-get remove -y '^aspnetcore-.*'] failed to complete successfully. Proceeding..."
-          sudo apt-get remove -y '^dotnet-.*' --fix-missing || echo "::warning::The command [sudo apt-get remove -y '^dotnet-.*' --fix-missing] failed to complete successfully. Proceeding..."
-          sudo apt-get remove -y '^llvm-.*' --fix-missing || echo "::warning::The command [sudo apt-get remove -y '^llvm-.*' --fix-missing] failed to complete successfully. Proceeding..."
-          sudo apt-get remove -y 'php.*' --fix-missing || echo "::warning::The command [sudo apt-get remove -y 'php.*' --fix-missing] failed to complete successfully. Proceeding..."
-          sudo apt-get remove -y '^mongodb-.*' --fix-missing || echo "::warning::The command [sudo apt-get remove -y '^mongodb-.*' --fix-missing] failed to complete successfully. Proceeding..."
-          sudo apt-get remove -y '^mysql-.*' --fix-missing || echo "::warning::The command [sudo apt-get remove -y '^mysql-.*' --fix-missing] failed to complete successfully. Proceeding..."
-          sudo apt-get remove -y azure-cli google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri --fix-missing || echo "::warning::The command [sudo apt-get remove -y azure-cli google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri --fix-missing] failed to complete successfully. Proceeding..."
-          sudo apt-get remove -y google-cloud-sdk --fix-missing || echo "::debug::The command [sudo apt-get remove -y google-cloud-sdk --fix-missing] failed to complete successfully. Proceeding..."
-          sudo apt-get remove -y google-cloud-cli --fix-missing || echo "::debug::The command [sudo apt-get remove -y google-cloud-cli --fix-missing] failed to complete successfully. Proceeding..."
-          sudo apt-get autoremove -y || echo "::warning::The command [sudo apt-get autoremove -y] failed to complete successfully. Proceeding..."
-          sudo apt-get clean || echo "::warning::The command [sudo apt-get clean] failed to complete successfully. Proceeding..."
+          run apt-get remove -y '^aspnetcore-.*' || echo "::warning::The command [run apt-get remove -y '^aspnetcore-.*'] failed to complete successfully. Proceeding..."
+          run apt-get remove -y '^dotnet-.*' --fix-missing || echo "::warning::The command [run apt-get remove -y '^dotnet-.*' --fix-missing] failed to complete successfully. Proceeding..."
+          run apt-get remove -y '^llvm-.*' --fix-missing || echo "::warning::The command [run apt-get remove -y '^llvm-.*' --fix-missing] failed to complete successfully. Proceeding..."
+          run apt-get remove -y 'php.*' --fix-missing || echo "::warning::The command [run apt-get remove -y 'php.*' --fix-missing] failed to complete successfully. Proceeding..."
+          run apt-get remove -y '^mongodb-.*' --fix-missing || echo "::warning::The command [run apt-get remove -y '^mongodb-.*' --fix-missing] failed to complete successfully. Proceeding..."
+          run apt-get remove -y '^mysql-.*' --fix-missing || echo "::warning::The command [run apt-get remove -y '^mysql-.*' --fix-missing] failed to complete successfully. Proceeding..."
+          run apt-get remove -y azure-cli google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri --fix-missing || echo "::warning::The command [run apt-get remove -y azure-cli google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri --fix-missing] failed to complete successfully. Proceeding..."
+          run apt-get remove -y google-cloud-sdk --fix-missing || echo "::debug::The command [run apt-get remove -y google-cloud-sdk --fix-missing] failed to complete successfully. Proceeding..."
+          run apt-get remove -y google-cloud-cli --fix-missing || echo "::debug::The command [run apt-get remove -y google-cloud-cli --fix-missing] failed to complete successfully. Proceeding..."
+          run apt-get autoremove -y || echo "::warning::The command [run apt-get autoremove -y] failed to complete successfully. Proceeding..."
+          run apt-get clean || echo "::warning::The command [run apt-get clean] failed to complete successfully. Proceeding..."
 
           AFTER=$(getAvailableSpace)
           SAVED=$((AFTER-BEFORE))
@@ -202,7 +214,7 @@ runs:
         if [[ ${{ inputs.docker-images }} == 'true' ]]; then
           BEFORE=$(getAvailableSpace)
 
-          sudo docker image prune --all --force || true
+          run docker image prune --all --force || true
 
           AFTER=$(getAvailableSpace)
           SAVED=$((AFTER-BEFORE))
@@ -215,7 +227,7 @@ runs:
         if [[ ${{ inputs.tool-cache }} == 'true' ]]; then
           BEFORE=$(getAvailableSpace)
 
-          sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true
+          run rm -rf "$AGENT_TOOLSDIRECTORY" || true
           
           AFTER=$(getAvailableSpace)
           SAVED=$((AFTER-BEFORE))
@@ -227,8 +239,8 @@ runs:
         if [[ ${{ inputs.swap-storage }} == 'true' ]]; then
           BEFORE=$(getAvailableSpace)
 
-          sudo swapoff -a || true
-          sudo rm -f '${{ inputs.chroot }}/mnt/swapfile' || true
+          run swapoff -a || true
+          run rm -f '${{ inputs.chroot }}/mnt/swapfile' || true
           free -h
           
           AFTER=$(getAvailableSpace)
@@ -240,7 +252,7 @@ runs:
 
         # Output saved space statistic
 
-        AVAILABLE_END=$(getAvailableSpace '${{ inputs.chroot }}')
+        AVAILABLE_END=$(getAvailableSpace)
         AVAILABLE_ROOT_END=$(getAvailableSpace '${{ inputs.chroot }}/')
 
         echo ""
